# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import person_service_pb2 as person__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in person_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PersonServiceStub:
    """============================================================================

    SERVICE DEFINITION

    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePerson = channel.unary_unary(
                '/omnitest.polyglot.nexus.PersonService/CreatePerson',
                request_serializer=person__service__pb2.CreatePersonRequest.SerializeToString,
                response_deserializer=person__service__pb2.CreatePersonResponse.FromString,
                _registered_method=True)
        self.ReadAllPersons = channel.unary_unary(
                '/omnitest.polyglot.nexus.PersonService/ReadAllPersons',
                request_serializer=person__service__pb2.ReadAllPersonsRequest.SerializeToString,
                response_deserializer=person__service__pb2.PersonListResponse.FromString,
                _registered_method=True)
        self.SearchByFilter = channel.unary_unary(
                '/omnitest.polyglot.nexus.PersonService/SearchByFilter',
                request_serializer=person__service__pb2.FilterSearchRequest.SerializeToString,
                response_deserializer=person__service__pb2.PersonListResponse.FromString,
                _registered_method=True)
        self.SearchByVector = channel.unary_unary(
                '/omnitest.polyglot.nexus.PersonService/SearchByVector',
                request_serializer=person__service__pb2.VectorSearchRequest.SerializeToString,
                response_deserializer=person__service__pb2.PersonListResponse.FromString,
                _registered_method=True)


class PersonServiceServicer:
    """============================================================================

    SERVICE DEFINITION

    ============================================================================

    """

    def CreatePerson(self, request, context):
        """1. Write: Insert data

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadAllPersons(self, request, context):
        """2. Read: Paginated retrieval

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchByFilter(self, request, context):
        """3. Search: Traditional SQL filtering

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchByVector(self, request, context):
        """4. AI Search: Vector similarity (HNSW index)

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PersonServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePerson': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePerson,
                    request_deserializer=person__service__pb2.CreatePersonRequest.FromString,
                    response_serializer=person__service__pb2.CreatePersonResponse.SerializeToString,
            ),
            'ReadAllPersons': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadAllPersons,
                    request_deserializer=person__service__pb2.ReadAllPersonsRequest.FromString,
                    response_serializer=person__service__pb2.PersonListResponse.SerializeToString,
            ),
            'SearchByFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchByFilter,
                    request_deserializer=person__service__pb2.FilterSearchRequest.FromString,
                    response_serializer=person__service__pb2.PersonListResponse.SerializeToString,
            ),
            'SearchByVector': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchByVector,
                    request_deserializer=person__service__pb2.VectorSearchRequest.FromString,
                    response_serializer=person__service__pb2.PersonListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'omnitest.polyglot.nexus.PersonService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('omnitest.polyglot.nexus.PersonService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PersonService:
    """============================================================================

    SERVICE DEFINITION

    ============================================================================

    """

    @staticmethod
    def CreatePerson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omnitest.polyglot.nexus.PersonService/CreatePerson',
            person__service__pb2.CreatePersonRequest.SerializeToString,
            person__service__pb2.CreatePersonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadAllPersons(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omnitest.polyglot.nexus.PersonService/ReadAllPersons',
            person__service__pb2.ReadAllPersonsRequest.SerializeToString,
            person__service__pb2.PersonListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchByFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omnitest.polyglot.nexus.PersonService/SearchByFilter',
            person__service__pb2.FilterSearchRequest.SerializeToString,
            person__service__pb2.PersonListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchByVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omnitest.polyglot.nexus.PersonService/SearchByVector',
            person__service__pb2.VectorSearchRequest.SerializeToString,
            person__service__pb2.PersonListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
